// <auto-generated />
using System;
using FridgeSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FridgeSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251013094924_update tables")]
    partial class updatetables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FridgeSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FridgeSystem.Models.AssignedFault", b =>
                {
                    b.Property<int>("AssignedFaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedFaultId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaultTechId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeFaultId")
                        .HasColumnType("int");

                    b.HasKey("AssignedFaultId");

                    b.HasIndex("FaultTechId");

                    b.HasIndex("FridgeFaultId");

                    b.ToTable("AssignedFaults");
                });

            modelBuilder.Entity("FridgeSystem.Models.Customer", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ProfileActive")
                        .HasColumnType("bit");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerFridge", b =>
                {
                    b.Property<int>("CustomerFridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerFridgeId"));

                    b.Property<int>("CustomerLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePickedUp")
                        .HasColumnType("datetime2");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerFridgeId");

                    b.HasIndex("CustomerLocationId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("CustomerFridges");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerLocation", b =>
                {
                    b.Property<int>("CustomerLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerLocationId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerLocationId");

                    b.HasIndex("BusinessId");

                    b.ToTable("CustomerLocations");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<int>("FaultReportFaultId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("FaultReportFaultId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("CustomersNotifications");
                });

            modelBuilder.Entity("FridgeSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FridgeSystem.Models.EmployeeNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeesNotifications");
                });

            modelBuilder.Entity("FridgeSystem.Models.EventType", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventId");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultDiagnostic", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FaultId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("FaultDiagnostics");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultReport", b =>
                {
                    b.Property<int>("FaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultId"));

                    b.Property<int>("AdminEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerBusinessId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FaultId");

                    b.HasIndex("AdminEmployeeId");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CustomerBusinessId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("FaultReports");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultTechnician", b =>
                {
                    b.Property<int>("FaultTechId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultTechId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CurrentActiveFaultCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFaultAssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("FaultTechId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("FaultTechnicians");
                });

            modelBuilder.Entity("FridgeSystem.Models.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FaultReportFaultId")
                        .HasColumnType("int");

                    b.Property<string>("FridgeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FridgeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WarrantyExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("FridgeId");

                    b.HasIndex("CustomerLocationId");

                    b.HasIndex("FaultReportFaultId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Fridges");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<int>("AllocatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessNameBusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("AllocatedById");

                    b.HasIndex("BusinessNameBusinessId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RequestId");

                    b.ToTable("FridgesAllocations");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeFault", b =>
                {
                    b.Property<int>("FridgeFaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeFaultId"));

                    b.Property<int>("CustomerFridgeId")
                        .HasColumnType("int");

                    b.Property<string>("FaultDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoggedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FridgeFaultId");

                    b.HasIndex("CustomerFridgeId");

                    b.ToTable("FridgeFaults");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryLiasonEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagedById")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryLiasonEmployeeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("FridgesInventory");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerLocationId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreferredPickup")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CustomerLocationId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("WarehouseId");

                    b.ToTable("FridgeRequests");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeRequestItem", b =>
                {
                    b.Property<int>("FridgeRequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeRequestItemId"));

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("FridgeRequestItemId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("RequestId");

                    b.ToTable("FridgeRequestItems");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("HistoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EventId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("FridgeStatusHistory");
                });

            modelBuilder.Entity("FridgeSystem.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RequestedById");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("AssignedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FaultId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ServiceAssignments");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceCheckItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ChecklistId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<int>("ServiceChecklistChecklistId")
                        .HasColumnType("int");

                    b.Property<string>("StepDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("ServiceChecklistChecklistId");

                    b.ToTable("serviceCheckItems");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceCheckResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("CheckedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("CheckedById");

                    b.HasIndex("ItemId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ServiceCheckResults");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceChecklist", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistId"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChecklistId");

                    b.HasIndex("CreatedById");

                    b.ToTable("ServiceChecklists");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EventId");

                    b.HasIndex("FaultId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("LocationId");

                    b.ToTable("ServiceSchedules");
                });

            modelBuilder.Entity("FridgeSystem.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("FridgeSystem.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("FridgeSystem.Models.WarehouseStock", b =>
                {
                    b.Property<int>("WarehouseStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseStockId"));

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("WarehouseStockId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("WarehouseId", "FridgeId")
                        .IsUnique();

                    b.ToTable("WarehouseStocks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FridgeSystem.Models.AssignedFault", b =>
                {
                    b.HasOne("FridgeSystem.Models.FaultTechnician", "Technician")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("FaultTechId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FridgeFault", "FridgeFault")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("FridgeFaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FridgeFault");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FridgeSystem.Models.Customer", b =>
                {
                    b.HasOne("FridgeSystem.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("FridgeSystem.Models.Customer", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerFridge", b =>
                {
                    b.HasOne("FridgeSystem.Models.CustomerLocation", "CustomerLocation")
                        .WithMany("CustomerFridges")
                        .HasForeignKey("CustomerLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerLocation");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerLocation", b =>
                {
                    b.HasOne("FridgeSystem.Models.Customer", "Customer")
                        .WithMany("CustomerLocations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerNotification", b =>
                {
                    b.HasOne("FridgeSystem.Models.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FaultReport", "FaultReport")
                        .WithMany("Notifications")
                        .HasForeignKey("FaultReportFaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.ServiceSchedule", "Schedule")
                        .WithMany("Notifications")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("FaultReport");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FridgeSystem.Models.Employee", b =>
                {
                    b.HasOne("FridgeSystem.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FridgeSystem.Models.EmployeeNotification", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultDiagnostic", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "Employee")
                        .WithMany("Diagnostics")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FaultReport", "FaultReport")
                        .WithMany("Diagnostics")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.ServiceSchedule", "Schedule")
                        .WithMany("FaultDiagnostics")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("FaultReport");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultReport", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "Admin")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("AdminEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Employee", "FaultTechnician")
                        .WithMany("AllocatedFaults")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FridgeSystem.Models.Customer", "Customer")
                        .WithMany("FaultReports")
                        .HasForeignKey("CustomerBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FridgeInventory", "FridgeInventory")
                        .WithMany("FaultReports")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.CustomerLocation", "Location")
                        .WithMany("FaultReports")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("FaultTechnician");

                    b.Navigation("FridgeInventory");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultTechnician", b =>
                {
                    b.HasOne("FridgeSystem.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Technician")
                        .HasForeignKey("FridgeSystem.Models.FaultTechnician", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Warehouse", "Warehouse")
                        .WithMany("FaultTechnicians")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FridgeSystem.Models.Fridge", b =>
                {
                    b.HasOne("FridgeSystem.Models.CustomerLocation", "CustomerLocation")
                        .WithMany("Fridges")
                        .HasForeignKey("CustomerLocationId");

                    b.HasOne("FridgeSystem.Models.FaultReport", null)
                        .WithMany("Fridges")
                        .HasForeignKey("FaultReportFaultId");

                    b.HasOne("FridgeSystem.Models.FridgeInventory", "Inventory")
                        .WithMany("Fridges")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FridgeSystem.Models.Supplier", "Supplier")
                        .WithMany("SuppliedFridges")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CustomerLocation");

                    b.Navigation("Inventory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeAllocation", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "CustomerLiaison")
                        .WithMany("Allocations")
                        .HasForeignKey("AllocatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Customer", "BusinessName")
                        .WithMany()
                        .HasForeignKey("BusinessNameBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Fridge", "Fridge")
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FridgeInventory", "FridgeInventory")
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.CustomerLocation", "CustomerLocation")
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FridgeRequest", "FridgeRequest")
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessName");

                    b.Navigation("CustomerLiaison");

                    b.Navigation("CustomerLocation");

                    b.Navigation("Fridge");

                    b.Navigation("FridgeInventory");

                    b.Navigation("FridgeRequest");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeFault", b =>
                {
                    b.HasOne("FridgeSystem.Models.CustomerFridge", "CustomerFridge")
                        .WithMany("FridgeFaults")
                        .HasForeignKey("CustomerFridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerFridge");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeInventory", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "InventoryLiason")
                        .WithMany("ManagedInventories")
                        .HasForeignKey("InventoryLiasonEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Supplier", "Supplier")
                        .WithMany("FridgeModels")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryLiason");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeRequest", b =>
                {
                    b.HasOne("FridgeSystem.Models.Customer", "Customer")
                        .WithMany("FridgeRequests")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.CustomerLocation", "CustomerLocation")
                        .WithMany("FridgeRequests")
                        .HasForeignKey("CustomerLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FridgeInventory", "Inventory")
                        .WithMany("FridgeRequests")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Employee", "ReviewedBy")
                        .WithMany("FridgeRequests")
                        .HasForeignKey("ReviewedById");

                    b.HasOne("FridgeSystem.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerLocation");

                    b.Navigation("Inventory");

                    b.Navigation("ReviewedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeRequestItem", b =>
                {
                    b.HasOne("FridgeSystem.Models.Fridge", "Fridge")
                        .WithMany("FridgeRequestItems")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FridgeRequest", "FridgeRequest")
                        .WithMany("FridgeRequestItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("FridgeRequest");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeStatusHistory", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "Employee")
                        .WithMany("FridgeStatusHistory")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.EventType", "EventType")
                        .WithMany("FridgeStatusHistory")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Fridge", null)
                        .WithMany("FridgeStatusHistory")
                        .HasForeignKey("FridgeId");

                    b.HasOne("FridgeSystem.Models.FridgeInventory", "FridgeInventory")
                        .WithMany("FridgeStatusHistory")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.CustomerLocation", "Location")
                        .WithMany("FridgeStatusHistory")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EventType");

                    b.Navigation("FridgeInventory");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FridgeSystem.Models.PurchaseRequest", b =>
                {
                    b.HasOne("FridgeSystem.Models.FridgeInventory", "Inventory")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Employee", "Manager")
                        .WithMany("PurchaseRequestsSubmitted")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Employee", "RequestedBy")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Manager");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceAssignment", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "AssignedBy")
                        .WithMany("ServicesAssigned")
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Employee", "Technician")
                        .WithMany("AssignedServices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FaultReport", "FaultReport")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.ServiceSchedule", "Schedule")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("FaultReport");

                    b.Navigation("Schedule");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceCheckItem", b =>
                {
                    b.HasOne("FridgeSystem.Models.ServiceChecklist", "ServiceChecklist")
                        .WithMany("Items")
                        .HasForeignKey("ServiceChecklistChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceChecklist");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceCheckResult", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "CheckedBy")
                        .WithMany("ServiceCheckresults")
                        .HasForeignKey("CheckedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.ServiceCheckItem", "Item")
                        .WithMany("ServiceCheckResults")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.ServiceSchedule", "ServiceSchedule")
                        .WithMany("ServiceCheckResults")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckedBy");

                    b.Navigation("Item");

                    b.Navigation("ServiceSchedule");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceChecklist", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "CreatedBy")
                        .WithMany("ServiceChecklists")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceSchedule", b =>
                {
                    b.HasOne("FridgeSystem.Models.Employee", "Employee")
                        .WithMany("ServiceSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.EventType", "ServiceType")
                        .WithMany("ServiceSchedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.FaultReport", "FaultReport")
                        .WithMany("Schedules")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Fridge", "Fridge")
                        .WithMany("ServiceSchedules")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.CustomerLocation", "CustomerLocation")
                        .WithMany("ServiceSchedules")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerLocation");

                    b.Navigation("Employee");

                    b.Navigation("FaultReport");

                    b.Navigation("Fridge");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("FridgeSystem.Models.WarehouseStock", b =>
                {
                    b.HasOne("FridgeSystem.Models.Fridge", "Fridge")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.Warehouse", "Warehouse")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FridgeSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FridgeSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FridgeSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FridgeSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FridgeSystem.Models.Customer", b =>
                {
                    b.Navigation("CustomerLocations");

                    b.Navigation("FaultReports");

                    b.Navigation("FridgeRequests");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerFridge", b =>
                {
                    b.Navigation("FridgeFaults");
                });

            modelBuilder.Entity("FridgeSystem.Models.CustomerLocation", b =>
                {
                    b.Navigation("CustomerFridges");

                    b.Navigation("FaultReports");

                    b.Navigation("FridgeAllocations");

                    b.Navigation("FridgeRequests");

                    b.Navigation("FridgeStatusHistory");

                    b.Navigation("Fridges");

                    b.Navigation("ServiceSchedules");
                });

            modelBuilder.Entity("FridgeSystem.Models.Employee", b =>
                {
                    b.Navigation("AllocatedFaults");

                    b.Navigation("Allocations");

                    b.Navigation("AssignedFaults");

                    b.Navigation("AssignedServices");

                    b.Navigation("Diagnostics");

                    b.Navigation("FridgeRequests");

                    b.Navigation("FridgeStatusHistory");

                    b.Navigation("ManagedInventories");

                    b.Navigation("Notifications");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("PurchaseRequestsSubmitted");

                    b.Navigation("ServiceChecklists");

                    b.Navigation("ServiceCheckresults");

                    b.Navigation("ServiceSchedules");

                    b.Navigation("ServicesAssigned");
                });

            modelBuilder.Entity("FridgeSystem.Models.EventType", b =>
                {
                    b.Navigation("FridgeStatusHistory");

                    b.Navigation("ServiceSchedules");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultReport", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Fridges");

                    b.Navigation("Notifications");

                    b.Navigation("Schedules");

                    b.Navigation("ServiceAssignments");
                });

            modelBuilder.Entity("FridgeSystem.Models.FaultTechnician", b =>
                {
                    b.Navigation("AssignedFaults");
                });

            modelBuilder.Entity("FridgeSystem.Models.Fridge", b =>
                {
                    b.Navigation("FridgeAllocations");

                    b.Navigation("FridgeRequestItems");

                    b.Navigation("FridgeStatusHistory");

                    b.Navigation("ServiceSchedules");

                    b.Navigation("WarehouseStocks");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeFault", b =>
                {
                    b.Navigation("AssignedFaults");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeInventory", b =>
                {
                    b.Navigation("FaultReports");

                    b.Navigation("FridgeAllocations");

                    b.Navigation("FridgeRequests");

                    b.Navigation("FridgeStatusHistory");

                    b.Navigation("Fridges");

                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("FridgeSystem.Models.FridgeRequest", b =>
                {
                    b.Navigation("FridgeAllocations");

                    b.Navigation("FridgeRequestItems");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceCheckItem", b =>
                {
                    b.Navigation("ServiceCheckResults");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceChecklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FridgeSystem.Models.ServiceSchedule", b =>
                {
                    b.Navigation("FaultDiagnostics");

                    b.Navigation("Notifications");

                    b.Navigation("ServiceAssignments");

                    b.Navigation("ServiceCheckResults");
                });

            modelBuilder.Entity("FridgeSystem.Models.Supplier", b =>
                {
                    b.Navigation("FridgeModels");

                    b.Navigation("SuppliedFridges");
                });

            modelBuilder.Entity("FridgeSystem.Models.Warehouse", b =>
                {
                    b.Navigation("FaultTechnicians");

                    b.Navigation("WarehouseStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
